export const INCREMENT_REQUEST = "INCREMENT_REQUEST";
export const INCREMENT_SUCCESS = "INCREMENT_SUCCESS";
export const INCREMENT_FAILURE = "INCREMENT_FAILURE";

export const DECREMENT_REQUEST = "DECREMENT_REQUEST";
export const DECREMENT_SUCCESS = "DECREMENT_SUCCESS";
export const DECREMENT_FAILURE = "DECREMENT_FAILURE";
